cal-overflow/Build-A-Blog

- src/components/BlogFeed.vue
- src/components/ContactForm.vue
- src/components/Divider.vue
- src/components/FooterBar.vue
- src/components/Home.vue
- src/components/NavBar.vue
- src/components/NavItem.vue
- src/components/previews/Blog.vue
- src/components/previews/Portfolio.vue
- src/components/previews/Post.vue
- src/layouts/default.vue
- src/layouts/error.vue
- src/layouts/initializeTheme.js
- src/pages/contact.vue
- src/pages/post/_.vue
- src/tailwind.config.js
- test/unit/components/NavItem.spec.js
> Enable dark mode toggle

- src/components/ContactForm.vue
- test/unit/components/ContactForm.spec.js
> Scrape the query for app version (Contact Form)

- src/layouts/default.vue
This PR adds smooth scrolling. I decided not to implement anchor links.
Resolves #82
> Smooth scrolling

- src/components/Home.vue
> Fix home screen lazy loading content width

- README.md
- nuxt.config.js
- src/components/ContactForm.vue
- src/components/FooterBar.vue
- src/components/Home.vue
- src/components/NavBar.vue
- test/e2e/integration/pages/contact.spec.js
- test/e2e/integration/pages/index.spec.js
- test/unit/components/ContactForm.spec.js
- test/unit/components/FooterBar.spec.js
- test/unit/components/Home.spec.js
- test/unit/components/NavBar.spec.js
This PR includes changes that further seperates the content from the components. This allows the project to be more "modular" and makes it easier for someone else to scaffold into their own website.
Elaborate documentation has also been added to the repository's README.
> Seperate content and components

- .eslintrc.js
- .github/workflows/ci.yml
- package-lock.json
- package.json
- test/e2e/integration/components/backToTopButton.spec.js
- test/e2e/integration/components/footer.spec.js
- test/e2e/integration/components/navBar.spec.js
- test/e2e/integration/pages/blog.spec.js
- test/e2e/integration/pages/contact.spec.js
- test/e2e/integration/pages/index.spec.js
- test/e2e/integration/pages/post.spec.js
- test/e2e/plugins.js
This PR updates the e2e tests so that they are passing even for a barebones repository. The tests will fail given the repository is cloned with no changes due to required environment variables. However, this further encourages users to define those required environment variables.
Resolves #125
> Fix e2e tests

- src/content/general/about.md
- src/content/general/blog-preview.md
- src/content/general/portfolio-preview.md
- src/content/posts/001-hello-world.md
- test/e2e/integration/components/backToTopButton.spec.js
- test/e2e/integration/pages/blog.spec.js
- test/e2e/integration/pages/post.spec.js
Closes #129 
Also includes small improvements to e2e tests to prevent flakiness.
> 👨‍🔧 Fix broken links

- README.md
- cypress.json
This PR includes documentation to help configure e2e (cypress) test recordings.
> 📸 e2e test recording

- .github/workflows/ci.yml
- README.md
- src/content/general/about.md
- src/content/general/blog-preview.md
- src/content/general/portfolio-preview.md
- src/content/posts/001-hello-world.md
- src/pages/category/_.vue
- src/pages/post/_.vue
- test/e2e/integration/components/footer.spec.js
This PR brings minor improvements to the e2e tests. Cleanup and outdated references are also included.
> 🧪 Update e2e tests

- src/components/CategoryDropdown.vue
- src/components/CategoryList.vue
- src/components/previews/Category.vue
- src/components/previews/Post.vue
- test/unit/components/preview/Category.spec.js
Improve styling issues from previous PR #136 
Note that there is a warning in the tests that I cannot seem to fix. The test is still functioning properly, so I am going to ignore the warning for now.
> 🎨 Fix styling issues

- CODEOWNERS
- src/components/previews/Category.vue
Adds dark text styling attribute to Latest Posts in categories.
> Added dark text to latest posts

- README.md
- src/components/TagList.vue
- src/content/posts/001-hello-world.md
- src/pages/post/_.vue
Includes several small UI changes. Additional updates to README.
Closes #141
> Small UI feature batch

- src/components/navigation/TagList.vue
- src/pages/post/_.vue
fixed two import bugs; the components where used but never imported.
> fix import bugs

- nuxt.config.js
- src/components/views/Post.vue
- src/components/views/PostFeed.vue
- src/pages/post/_.vue
- test/e2e/integration/components/backToTopButton.spec.js
- test/e2e/integration/components/footer.spec.js
- test/e2e/integration/pages/blog.spec.js
- test/e2e/integration/pages/contact.spec.js
- test/e2e/integration/pages/error.spec.js
- test/e2e/integration/pages/index.spec.js
- test/e2e/integration/pages/portfolio.spec.js
- test/e2e/integration/pages/post.spec.js
- test/helpers/postGenerator.js
- test/unit/components/ContactForm.spec.js
- test/unit/components/Divider.spec.js
- test/unit/components/NavBar.spec.js
- test/unit/components/NavItem.spec.js
- test/unit/components/Post.spec.js
- test/unit/components/PostFeed.spec.js
- test/unit/components/TagDropdown.spec.js
- test/unit/components/ToolTip.spec.js
- test/unit/components/preview/Page.spec.js
- test/unit/components/preview/Post.spec.js
- test/unit/components/preview/Tag.spec.js
- test/unit/layouts/error.spec.js
- test/unit/pages/post/_.spec.js
This mostly split /pages/post/_.vue into two files. Now the _.vue file calls a /components/views/Post.vue file. I also split the testing and finally ran the linter.
> create /views/Post.vue along with tests. Ran linter

- src/components/views/TagFeed.vue
- src/pages/tags.vue
- test/unit/components/TagFeed.spec.js
- test/unit/pages/tags.spec.js
you were there lol
Co-authored-by: cal <cal-overflow@users.noreply.github.com>
> split tags.vue into tags.vue and TagFeed.vue. Split testing also

- .github/workflows/template.deploy.yml
- .github/workflows/template.pr-validation.yml
- nuxt.config.js
- package-lock.json
- package.json
- src/components/views/PostFeed.vue
- src/pages/_.vue
- test/e2e/integration/pages/blog.spec.js
- test/unit/components/PostFeed.spec.js
This PR revives RSS support on the site and creates a different RSS feed for each section.
Closes #132 
Also includes slight adjustments to the deploy on `main` to fix the e2e tests from failing.
> RSS Sections

- src/components/views/Post.vue
Improvements to the styling on images embedded within posts.
closes #147
> Post `<img />` style

- src/components/development/Editor.vue
- src/components/previews/Post.vue
- src/components/views/Post.vue
- src/components/views/PostFeed.vue
- src/pages/_.vue
- test/unit/components/Post.spec.js
- test/unit/components/PostFeed.spec.js
- test/unit/components/preview/Post.spec.js
Migrate feature images to the `blog/` directory.
> Move feature images to `src/content`

- README.md
- src/pages/_.vue
Restore the basic post sorting on the post-feed view. This is temporary until #148 is implemented.
Also includes minor changes to the README
> Restore basic post sorting

- .github/workflows/template.deploy.yml
- README.md
- nuxt.config.js
- package-lock.json
- package.json
Add the ability to connect Google Analytics tracking by simply adding an environment variable at site build time.
Closes #171
> Google analytics integration

- README.md
- nuxt.config.js
- package-lock.json
- package.json
- src/components/views/Post.vue
- src/pages/_.vue
- src/pages/index.vue
- template/README.md
- template/deploy.sh
- template/google-analytics-tag.html
- test/unit/components/Post.spec.js
Removes outdated nuxt/google-analytics dependency introduced in https://github.com/cal-overflow/portfolio/pull/172
Adds google analytics tracking injection logic
---
Also fixes the following:
Closes #174 
Closes #173
> Fix google analytics tracking

- src/components/helpers/Card.vue
- src/components/previews/Post.vue
- src/components/views/Home.vue
- src/components/views/Post.vue
> Remove backticks from inline code

- src/components/previews/Post.vue
Smallest PR of all time? 👀
Closes #184
> 🚫 Disable unwanted post preview pointer events

- src/components/views/PostFeed.vue
Trying to make the UI somewhat decent is so time consuming 🥱
> 👁️👄👁️ Cleanup styling

- README.md
- src/components/previews/Post.vue
- src/components/views/Post.vue
> 🖼️ Image enhancements

- src/components/views/Post.vue
> 📋 Post improvements

- src/components/previews/Post.vue
- src/components/views/Home.vue
- src/components/views/Post.vue
- test/unit/components/views/Home.spec.js
Closes #205 
Added notes to #195 so it should be easier to implement.
> Optional image styling

- CODEOWNERS
- src/components/cards/RepositoryCard.vue
- src/components/previews/Github.vue
- src/components/views/Home.vue
- src/components/views/PostFeed.vue
- test/e2e/integration/pages/index.spec.js
Closes #145 
There is a new component that would be a great spot for #143 implementation
> GitHub Repository feed
